sudo: required

services:
  - docker

before_install:
  # Install JFrog CLI
  - curl -fL https://getcli.jfrog.io | sh
  # Configure Artifactory instance with JFrog CLI
  - ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_PASSWORD --interactive false

script:
  # Build Docker image
  - docker build --rm=false -t $ARTIFACTORY_DOCKER_REPOSITORY/node-version:$TRAVIS_BUILD_NUMBER .
  - docker run -d -p 3000:3000 $ARTIFACTORY_DOCKER_REPOSITORY/node-version:$TRAVIS_BUILD_NUMBER; sleep 10
  - curl --retry 10 --retry-delay 5 -v http://localhost:3000

after_success:
  # Login to Artifactory docker registry
  - docker login -u $ARTIFACTORY_USER -p $ARTIFACTORY_PASSWORD $ARTIFACTORY_DOCKER_REPOSITORY
  # Push docker image to Artifactory using JFrog CLI
  - ./jfrog rt dp $ARTIFACTORY_DOCKER_REPOSITORY/node-version:$TRAVIS_BUILD_NUMBER docker-dev --build-name=travisci-docker-artifactory --build-number=$TRAVIS_BUILD_NUMBER
  # Capture environment variables and append it to build information
  - ./jfrog rt bce travisci-docker-artifactory $TRAVIS_BUILD_NUMBER
  # Publish build information to Artifactory using JFrog CLI
  - ./jfrog rt bp travisci-docker-artifactory $TRAVIS_BUILD_NUMBER
  # Promote Docker image to Staging Repo (Optional)
  - ./jfrog rt bpr travisci-docker-artifactory $TRAVIS_BUILD_NUMBER $DOCEKR_STAGE_REPO --status="Staged" --copy=true
  # Promote Docker image to Production Repo (Optional)
  - ./jfrog rt bpr travisci-docker-artifactory $TRAVIS_BUILD_NUMBER $DOCEKR_PROD_REPO --status="Promoted to Prod" --copy=true